/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL.impl;

import fr.pari10.miage.promo.promoDSL.Chapitre;
import fr.pari10.miage.promo.promoDSL.PromoDSLPackage;
import fr.pari10.miage.promo.promoDSL.Recette;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Chapitre</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.impl.ChapitreImpl#getNumDuChapitre <em>Num Du Chapitre</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.impl.ChapitreImpl#getRecette <em>Recette</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ChapitreImpl extends MinimalEObjectImpl.Container implements Chapitre
{
  /**
   * The default value of the '{@link #getNumDuChapitre() <em>Num Du Chapitre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumDuChapitre()
   * @generated
   * @ordered
   */
  protected static final String NUM_DU_CHAPITRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNumDuChapitre() <em>Num Du Chapitre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumDuChapitre()
   * @generated
   * @ordered
   */
  protected String numDuChapitre = NUM_DU_CHAPITRE_EDEFAULT;

  /**
   * The cached value of the '{@link #getRecette() <em>Recette</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecette()
   * @generated
   * @ordered
   */
  protected EList<Recette> recette;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChapitreImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PromoDSLPackage.Literals.CHAPITRE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNumDuChapitre()
  {
    return numDuChapitre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNumDuChapitre(String newNumDuChapitre)
  {
    String oldNumDuChapitre = numDuChapitre;
    numDuChapitre = newNumDuChapitre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PromoDSLPackage.CHAPITRE__NUM_DU_CHAPITRE, oldNumDuChapitre, numDuChapitre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Recette> getRecette()
  {
    if (recette == null)
    {
      recette = new EObjectContainmentEList<Recette>(Recette.class, this, PromoDSLPackage.CHAPITRE__RECETTE);
    }
    return recette;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PromoDSLPackage.CHAPITRE__RECETTE:
        return ((InternalEList<?>)getRecette()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PromoDSLPackage.CHAPITRE__NUM_DU_CHAPITRE:
        return getNumDuChapitre();
      case PromoDSLPackage.CHAPITRE__RECETTE:
        return getRecette();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PromoDSLPackage.CHAPITRE__NUM_DU_CHAPITRE:
        setNumDuChapitre((String)newValue);
        return;
      case PromoDSLPackage.CHAPITRE__RECETTE:
        getRecette().clear();
        getRecette().addAll((Collection<? extends Recette>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PromoDSLPackage.CHAPITRE__NUM_DU_CHAPITRE:
        setNumDuChapitre(NUM_DU_CHAPITRE_EDEFAULT);
        return;
      case PromoDSLPackage.CHAPITRE__RECETTE:
        getRecette().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PromoDSLPackage.CHAPITRE__NUM_DU_CHAPITRE:
        return NUM_DU_CHAPITRE_EDEFAULT == null ? numDuChapitre != null : !NUM_DU_CHAPITRE_EDEFAULT.equals(numDuChapitre);
      case PromoDSLPackage.CHAPITRE__RECETTE:
        return recette != null && !recette.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (numDuChapitre: ");
    result.append(numDuChapitre);
    result.append(')');
    return result.toString();
  }

} //ChapitreImpl
