/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL.impl;

import fr.pari10.miage.promo.promoDSL.Ingredient;
import fr.pari10.miage.promo.promoDSL.PromoDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ingredient</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.impl.IngredientImpl#getNomDuIng <em>Nom Du Ing</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.impl.IngredientImpl#getNum <em>Num</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.impl.IngredientImpl#getUnite <em>Unite</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IngredientImpl extends MinimalEObjectImpl.Container implements Ingredient
{
  /**
   * The default value of the '{@link #getNomDuIng() <em>Nom Du Ing</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNomDuIng()
   * @generated
   * @ordered
   */
  protected static final String NOM_DU_ING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNomDuIng() <em>Nom Du Ing</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNomDuIng()
   * @generated
   * @ordered
   */
  protected String nomDuIng = NOM_DU_ING_EDEFAULT;

  /**
   * The default value of the '{@link #getNum() <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNum()
   * @generated
   * @ordered
   */
  protected static final int NUM_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNum() <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNum()
   * @generated
   * @ordered
   */
  protected int num = NUM_EDEFAULT;

  /**
   * The default value of the '{@link #getUnite() <em>Unite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnite()
   * @generated
   * @ordered
   */
  protected static final String UNITE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUnite() <em>Unite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnite()
   * @generated
   * @ordered
   */
  protected String unite = UNITE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IngredientImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PromoDSLPackage.Literals.INGREDIENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNomDuIng()
  {
    return nomDuIng;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNomDuIng(String newNomDuIng)
  {
    String oldNomDuIng = nomDuIng;
    nomDuIng = newNomDuIng;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PromoDSLPackage.INGREDIENT__NOM_DU_ING, oldNomDuIng, nomDuIng));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getNum()
  {
    return num;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNum(int newNum)
  {
    int oldNum = num;
    num = newNum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PromoDSLPackage.INGREDIENT__NUM, oldNum, num));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getUnite()
  {
    return unite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnite(String newUnite)
  {
    String oldUnite = unite;
    unite = newUnite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PromoDSLPackage.INGREDIENT__UNITE, oldUnite, unite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PromoDSLPackage.INGREDIENT__NOM_DU_ING:
        return getNomDuIng();
      case PromoDSLPackage.INGREDIENT__NUM:
        return getNum();
      case PromoDSLPackage.INGREDIENT__UNITE:
        return getUnite();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PromoDSLPackage.INGREDIENT__NOM_DU_ING:
        setNomDuIng((String)newValue);
        return;
      case PromoDSLPackage.INGREDIENT__NUM:
        setNum((Integer)newValue);
        return;
      case PromoDSLPackage.INGREDIENT__UNITE:
        setUnite((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PromoDSLPackage.INGREDIENT__NOM_DU_ING:
        setNomDuIng(NOM_DU_ING_EDEFAULT);
        return;
      case PromoDSLPackage.INGREDIENT__NUM:
        setNum(NUM_EDEFAULT);
        return;
      case PromoDSLPackage.INGREDIENT__UNITE:
        setUnite(UNITE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PromoDSLPackage.INGREDIENT__NOM_DU_ING:
        return NOM_DU_ING_EDEFAULT == null ? nomDuIng != null : !NOM_DU_ING_EDEFAULT.equals(nomDuIng);
      case PromoDSLPackage.INGREDIENT__NUM:
        return num != NUM_EDEFAULT;
      case PromoDSLPackage.INGREDIENT__UNITE:
        return UNITE_EDEFAULT == null ? unite != null : !UNITE_EDEFAULT.equals(unite);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (NomDuIng: ");
    result.append(nomDuIng);
    result.append(", num: ");
    result.append(num);
    result.append(", unite: ");
    result.append(unite);
    result.append(')');
    return result.toString();
  }

} //IngredientImpl
