/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL.impl;

import fr.pari10.miage.promo.promoDSL.Instruction;
import fr.pari10.miage.promo.promoDSL.PromoDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Instruction</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.impl.InstructionImpl#getNumDuInstruction <em>Num Du Instruction</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InstructionImpl extends MinimalEObjectImpl.Container implements Instruction
{
  /**
   * The default value of the '{@link #getNumDuInstruction() <em>Num Du Instruction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumDuInstruction()
   * @generated
   * @ordered
   */
  protected static final String NUM_DU_INSTRUCTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNumDuInstruction() <em>Num Du Instruction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumDuInstruction()
   * @generated
   * @ordered
   */
  protected String numDuInstruction = NUM_DU_INSTRUCTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InstructionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PromoDSLPackage.Literals.INSTRUCTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNumDuInstruction()
  {
    return numDuInstruction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNumDuInstruction(String newNumDuInstruction)
  {
    String oldNumDuInstruction = numDuInstruction;
    numDuInstruction = newNumDuInstruction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PromoDSLPackage.INSTRUCTION__NUM_DU_INSTRUCTION, oldNumDuInstruction, numDuInstruction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PromoDSLPackage.INSTRUCTION__NUM_DU_INSTRUCTION:
        return getNumDuInstruction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PromoDSLPackage.INSTRUCTION__NUM_DU_INSTRUCTION:
        setNumDuInstruction((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PromoDSLPackage.INSTRUCTION__NUM_DU_INSTRUCTION:
        setNumDuInstruction(NUM_DU_INSTRUCTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PromoDSLPackage.INSTRUCTION__NUM_DU_INSTRUCTION:
        return NUM_DU_INSTRUCTION_EDEFAULT == null ? numDuInstruction != null : !NUM_DU_INSTRUCTION_EDEFAULT.equals(numDuInstruction);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (numDuInstruction: ");
    result.append(numDuInstruction);
    result.append(')');
    return result.toString();
  }

} //InstructionImpl
