/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL.impl;

import fr.pari10.miage.promo.promoDSL.Livre;
import fr.pari10.miage.promo.promoDSL.Modele;
import fr.pari10.miage.promo.promoDSL.PromoDSLPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Modele</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.impl.ModeleImpl#getLivre <em>Livre</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModeleImpl extends MinimalEObjectImpl.Container implements Modele
{
  /**
   * The cached value of the '{@link #getLivre() <em>Livre</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLivre()
   * @generated
   * @ordered
   */
  protected EList<Livre> livre;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModeleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PromoDSLPackage.Literals.MODELE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Livre> getLivre()
  {
    if (livre == null)
    {
      livre = new EObjectContainmentEList<Livre>(Livre.class, this, PromoDSLPackage.MODELE__LIVRE);
    }
    return livre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PromoDSLPackage.MODELE__LIVRE:
        return ((InternalEList<?>)getLivre()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PromoDSLPackage.MODELE__LIVRE:
        return getLivre();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PromoDSLPackage.MODELE__LIVRE:
        getLivre().clear();
        getLivre().addAll((Collection<? extends Livre>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PromoDSLPackage.MODELE__LIVRE:
        getLivre().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PromoDSLPackage.MODELE__LIVRE:
        return livre != null && !livre.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModeleImpl
