/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL.impl;

import fr.pari10.miage.promo.promoDSL.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PromoDSLFactoryImpl extends EFactoryImpl implements PromoDSLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static PromoDSLFactory init()
  {
    try
    {
      PromoDSLFactory thePromoDSLFactory = (PromoDSLFactory)EPackage.Registry.INSTANCE.getEFactory(PromoDSLPackage.eNS_URI);
      if (thePromoDSLFactory != null)
      {
        return thePromoDSLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new PromoDSLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PromoDSLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case PromoDSLPackage.MODELE: return createModele();
      case PromoDSLPackage.LIVRE: return createLivre();
      case PromoDSLPackage.CHAPITRE: return createChapitre();
      case PromoDSLPackage.RECETTE: return createRecette();
      case PromoDSLPackage.ALTERNATIVES: return createAlternatives();
      case PromoDSLPackage.INGREDIENT: return createIngredient();
      case PromoDSLPackage.INSTRUCTION: return createInstruction();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Modele createModele()
  {
    ModeleImpl modele = new ModeleImpl();
    return modele;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Livre createLivre()
  {
    LivreImpl livre = new LivreImpl();
    return livre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Chapitre createChapitre()
  {
    ChapitreImpl chapitre = new ChapitreImpl();
    return chapitre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Recette createRecette()
  {
    RecetteImpl recette = new RecetteImpl();
    return recette;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Alternatives createAlternatives()
  {
    AlternativesImpl alternatives = new AlternativesImpl();
    return alternatives;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Ingredient createIngredient()
  {
    IngredientImpl ingredient = new IngredientImpl();
    return ingredient;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Instruction createInstruction()
  {
    InstructionImpl instruction = new InstructionImpl();
    return instruction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PromoDSLPackage getPromoDSLPackage()
  {
    return (PromoDSLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static PromoDSLPackage getPackage()
  {
    return PromoDSLPackage.eINSTANCE;
  }

} //PromoDSLFactoryImpl
