/*
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPromoDSLScopeProvider extends DelegatingScopeProvider {
}
