/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alternatives</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Alternatives#getAltNum <em>Alt Num</em>}</li>
 * </ul>
 *
 * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getAlternatives()
 * @model
 * @generated
 */
public interface Alternatives extends EObject
{
  /**
   * Returns the value of the '<em><b>Alt Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alt Num</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt Num</em>' attribute.
   * @see #setAltNum(String)
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getAlternatives_AltNum()
   * @model
   * @generated
   */
  String getAltNum();

  /**
   * Sets the value of the '{@link fr.pari10.miage.promo.promoDSL.Alternatives#getAltNum <em>Alt Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt Num</em>' attribute.
   * @see #getAltNum()
   * @generated
   */
  void setAltNum(String value);

} // Alternatives
