/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ingredient</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Ingredient#getNomDuIng <em>Nom Du Ing</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Ingredient#getNum <em>Num</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Ingredient#getUnite <em>Unite</em>}</li>
 * </ul>
 *
 * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getIngredient()
 * @model
 * @generated
 */
public interface Ingredient extends EObject
{
  /**
   * Returns the value of the '<em><b>Nom Du Ing</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nom Du Ing</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom Du Ing</em>' attribute.
   * @see #setNomDuIng(String)
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getIngredient_NomDuIng()
   * @model
   * @generated
   */
  String getNomDuIng();

  /**
   * Sets the value of the '{@link fr.pari10.miage.promo.promoDSL.Ingredient#getNomDuIng <em>Nom Du Ing</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom Du Ing</em>' attribute.
   * @see #getNomDuIng()
   * @generated
   */
  void setNomDuIng(String value);

  /**
   * Returns the value of the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num</em>' attribute.
   * @see #setNum(int)
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getIngredient_Num()
   * @model
   * @generated
   */
  int getNum();

  /**
   * Sets the value of the '{@link fr.pari10.miage.promo.promoDSL.Ingredient#getNum <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num</em>' attribute.
   * @see #getNum()
   * @generated
   */
  void setNum(int value);

  /**
   * Returns the value of the '<em><b>Unite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unite</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unite</em>' attribute.
   * @see #setUnite(String)
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getIngredient_Unite()
   * @model
   * @generated
   */
  String getUnite();

  /**
   * Sets the value of the '{@link fr.pari10.miage.promo.promoDSL.Ingredient#getUnite <em>Unite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unite</em>' attribute.
   * @see #getUnite()
   * @generated
   */
  void setUnite(String value);

} // Ingredient
