/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Livre</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Livre#getNomDuLivre <em>Nom Du Livre</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Livre#getNomDuLauteur <em>Nom Du Lauteur</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Livre#getChapitre <em>Chapitre</em>}</li>
 * </ul>
 *
 * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getLivre()
 * @model
 * @generated
 */
public interface Livre extends EObject
{
  /**
   * Returns the value of the '<em><b>Nom Du Livre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nom Du Livre</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom Du Livre</em>' attribute.
   * @see #setNomDuLivre(String)
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getLivre_NomDuLivre()
   * @model
   * @generated
   */
  String getNomDuLivre();

  /**
   * Sets the value of the '{@link fr.pari10.miage.promo.promoDSL.Livre#getNomDuLivre <em>Nom Du Livre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom Du Livre</em>' attribute.
   * @see #getNomDuLivre()
   * @generated
   */
  void setNomDuLivre(String value);

  /**
   * Returns the value of the '<em><b>Nom Du Lauteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nom Du Lauteur</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom Du Lauteur</em>' attribute.
   * @see #setNomDuLauteur(String)
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getLivre_NomDuLauteur()
   * @model
   * @generated
   */
  String getNomDuLauteur();

  /**
   * Sets the value of the '{@link fr.pari10.miage.promo.promoDSL.Livre#getNomDuLauteur <em>Nom Du Lauteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom Du Lauteur</em>' attribute.
   * @see #getNomDuLauteur()
   * @generated
   */
  void setNomDuLauteur(String value);

  /**
   * Returns the value of the '<em><b>Chapitre</b></em>' containment reference list.
   * The list contents are of type {@link fr.pari10.miage.promo.promoDSL.Chapitre}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Chapitre</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chapitre</em>' containment reference list.
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getLivre_Chapitre()
   * @model containment="true"
   * @generated
   */
  EList<Chapitre> getChapitre();

} // Livre
