/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modele</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Modele#getLivre <em>Livre</em>}</li>
 * </ul>
 *
 * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getModele()
 * @model
 * @generated
 */
public interface Modele extends EObject
{
  /**
   * Returns the value of the '<em><b>Livre</b></em>' containment reference list.
   * The list contents are of type {@link fr.pari10.miage.promo.promoDSL.Livre}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Livre</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Livre</em>' containment reference list.
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getModele_Livre()
   * @model containment="true"
   * @generated
   */
  EList<Livre> getLivre();

} // Modele
