/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage
 * @generated
 */
public interface PromoDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PromoDSLFactory eINSTANCE = fr.pari10.miage.promo.promoDSL.impl.PromoDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Modele</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Modele</em>'.
   * @generated
   */
  Modele createModele();

  /**
   * Returns a new object of class '<em>Livre</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Livre</em>'.
   * @generated
   */
  Livre createLivre();

  /**
   * Returns a new object of class '<em>Chapitre</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Chapitre</em>'.
   * @generated
   */
  Chapitre createChapitre();

  /**
   * Returns a new object of class '<em>Recette</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Recette</em>'.
   * @generated
   */
  Recette createRecette();

  /**
   * Returns a new object of class '<em>Alternatives</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alternatives</em>'.
   * @generated
   */
  Alternatives createAlternatives();

  /**
   * Returns a new object of class '<em>Ingredient</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ingredient</em>'.
   * @generated
   */
  Ingredient createIngredient();

  /**
   * Returns a new object of class '<em>Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instruction</em>'.
   * @generated
   */
  Instruction createInstruction();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  PromoDSLPackage getPromoDSLPackage();

} //PromoDSLFactory
