/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.pari10.miage.promo.promoDSL.PromoDSLFactory
 * @model kind="package"
 * @generated
 */
public interface PromoDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "promoDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.pari10.fr/miage/promo/PromoDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "promoDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PromoDSLPackage eINSTANCE = fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.pari10.miage.promo.promoDSL.impl.ModeleImpl <em>Modele</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.pari10.miage.promo.promoDSL.impl.ModeleImpl
   * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getModele()
   * @generated
   */
  int MODELE = 0;

  /**
   * The feature id for the '<em><b>Livre</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODELE__LIVRE = 0;

  /**
   * The number of structural features of the '<em>Modele</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODELE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.pari10.miage.promo.promoDSL.impl.LivreImpl <em>Livre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.pari10.miage.promo.promoDSL.impl.LivreImpl
   * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getLivre()
   * @generated
   */
  int LIVRE = 1;

  /**
   * The feature id for the '<em><b>Nom Du Livre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIVRE__NOM_DU_LIVRE = 0;

  /**
   * The feature id for the '<em><b>Nom Du Lauteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIVRE__NOM_DU_LAUTEUR = 1;

  /**
   * The feature id for the '<em><b>Chapitre</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIVRE__CHAPITRE = 2;

  /**
   * The number of structural features of the '<em>Livre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIVRE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.pari10.miage.promo.promoDSL.impl.ChapitreImpl <em>Chapitre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.pari10.miage.promo.promoDSL.impl.ChapitreImpl
   * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getChapitre()
   * @generated
   */
  int CHAPITRE = 2;

  /**
   * The feature id for the '<em><b>Num Du Chapitre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAPITRE__NUM_DU_CHAPITRE = 0;

  /**
   * The feature id for the '<em><b>Recette</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAPITRE__RECETTE = 1;

  /**
   * The number of structural features of the '<em>Chapitre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAPITRE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.pari10.miage.promo.promoDSL.impl.RecetteImpl <em>Recette</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.pari10.miage.promo.promoDSL.impl.RecetteImpl
   * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getRecette()
   * @generated
   */
  int RECETTE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECETTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Num Photo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECETTE__NUM_PHOTO = 1;

  /**
   * The feature id for the '<em><b>Ingredients</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECETTE__INGREDIENTS = 2;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECETTE__INSTRUCTIONS = 3;

  /**
   * The feature id for the '<em><b>Alternatives</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECETTE__ALTERNATIVES = 4;

  /**
   * The number of structural features of the '<em>Recette</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECETTE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.pari10.miage.promo.promoDSL.impl.AlternativesImpl <em>Alternatives</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.pari10.miage.promo.promoDSL.impl.AlternativesImpl
   * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getAlternatives()
   * @generated
   */
  int ALTERNATIVES = 4;

  /**
   * The feature id for the '<em><b>Alt Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVES__ALT_NUM = 0;

  /**
   * The number of structural features of the '<em>Alternatives</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.pari10.miage.promo.promoDSL.impl.IngredientImpl <em>Ingredient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.pari10.miage.promo.promoDSL.impl.IngredientImpl
   * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getIngredient()
   * @generated
   */
  int INGREDIENT = 5;

  /**
   * The feature id for the '<em><b>Nom Du Ing</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENT__NOM_DU_ING = 0;

  /**
   * The feature id for the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENT__NUM = 1;

  /**
   * The feature id for the '<em><b>Unite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENT__UNITE = 2;

  /**
   * The number of structural features of the '<em>Ingredient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.pari10.miage.promo.promoDSL.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.pari10.miage.promo.promoDSL.impl.InstructionImpl
   * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 6;

  /**
   * The feature id for the '<em><b>Num Du Instruction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__NUM_DU_INSTRUCTION = 0;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link fr.pari10.miage.promo.promoDSL.Modele <em>Modele</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modele</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Modele
   * @generated
   */
  EClass getModele();

  /**
   * Returns the meta object for the containment reference list '{@link fr.pari10.miage.promo.promoDSL.Modele#getLivre <em>Livre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Livre</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Modele#getLivre()
   * @see #getModele()
   * @generated
   */
  EReference getModele_Livre();

  /**
   * Returns the meta object for class '{@link fr.pari10.miage.promo.promoDSL.Livre <em>Livre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Livre</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Livre
   * @generated
   */
  EClass getLivre();

  /**
   * Returns the meta object for the attribute '{@link fr.pari10.miage.promo.promoDSL.Livre#getNomDuLivre <em>Nom Du Livre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom Du Livre</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Livre#getNomDuLivre()
   * @see #getLivre()
   * @generated
   */
  EAttribute getLivre_NomDuLivre();

  /**
   * Returns the meta object for the attribute '{@link fr.pari10.miage.promo.promoDSL.Livre#getNomDuLauteur <em>Nom Du Lauteur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom Du Lauteur</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Livre#getNomDuLauteur()
   * @see #getLivre()
   * @generated
   */
  EAttribute getLivre_NomDuLauteur();

  /**
   * Returns the meta object for the containment reference list '{@link fr.pari10.miage.promo.promoDSL.Livre#getChapitre <em>Chapitre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Chapitre</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Livre#getChapitre()
   * @see #getLivre()
   * @generated
   */
  EReference getLivre_Chapitre();

  /**
   * Returns the meta object for class '{@link fr.pari10.miage.promo.promoDSL.Chapitre <em>Chapitre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chapitre</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Chapitre
   * @generated
   */
  EClass getChapitre();

  /**
   * Returns the meta object for the attribute '{@link fr.pari10.miage.promo.promoDSL.Chapitre#getNumDuChapitre <em>Num Du Chapitre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num Du Chapitre</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Chapitre#getNumDuChapitre()
   * @see #getChapitre()
   * @generated
   */
  EAttribute getChapitre_NumDuChapitre();

  /**
   * Returns the meta object for the containment reference list '{@link fr.pari10.miage.promo.promoDSL.Chapitre#getRecette <em>Recette</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Recette</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Chapitre#getRecette()
   * @see #getChapitre()
   * @generated
   */
  EReference getChapitre_Recette();

  /**
   * Returns the meta object for class '{@link fr.pari10.miage.promo.promoDSL.Recette <em>Recette</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recette</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Recette
   * @generated
   */
  EClass getRecette();

  /**
   * Returns the meta object for the attribute '{@link fr.pari10.miage.promo.promoDSL.Recette#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Recette#getName()
   * @see #getRecette()
   * @generated
   */
  EAttribute getRecette_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.pari10.miage.promo.promoDSL.Recette#getNumPhoto <em>Num Photo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num Photo</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Recette#getNumPhoto()
   * @see #getRecette()
   * @generated
   */
  EAttribute getRecette_NumPhoto();

  /**
   * Returns the meta object for the containment reference list '{@link fr.pari10.miage.promo.promoDSL.Recette#getIngredients <em>Ingredients</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ingredients</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Recette#getIngredients()
   * @see #getRecette()
   * @generated
   */
  EReference getRecette_Ingredients();

  /**
   * Returns the meta object for the containment reference list '{@link fr.pari10.miage.promo.promoDSL.Recette#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Recette#getInstructions()
   * @see #getRecette()
   * @generated
   */
  EReference getRecette_Instructions();

  /**
   * Returns the meta object for the containment reference list '{@link fr.pari10.miage.promo.promoDSL.Recette#getAlternatives <em>Alternatives</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Alternatives</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Recette#getAlternatives()
   * @see #getRecette()
   * @generated
   */
  EReference getRecette_Alternatives();

  /**
   * Returns the meta object for class '{@link fr.pari10.miage.promo.promoDSL.Alternatives <em>Alternatives</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alternatives</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Alternatives
   * @generated
   */
  EClass getAlternatives();

  /**
   * Returns the meta object for the attribute '{@link fr.pari10.miage.promo.promoDSL.Alternatives#getAltNum <em>Alt Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alt Num</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Alternatives#getAltNum()
   * @see #getAlternatives()
   * @generated
   */
  EAttribute getAlternatives_AltNum();

  /**
   * Returns the meta object for class '{@link fr.pari10.miage.promo.promoDSL.Ingredient <em>Ingredient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ingredient</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Ingredient
   * @generated
   */
  EClass getIngredient();

  /**
   * Returns the meta object for the attribute '{@link fr.pari10.miage.promo.promoDSL.Ingredient#getNomDuIng <em>Nom Du Ing</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom Du Ing</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Ingredient#getNomDuIng()
   * @see #getIngredient()
   * @generated
   */
  EAttribute getIngredient_NomDuIng();

  /**
   * Returns the meta object for the attribute '{@link fr.pari10.miage.promo.promoDSL.Ingredient#getNum <em>Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Ingredient#getNum()
   * @see #getIngredient()
   * @generated
   */
  EAttribute getIngredient_Num();

  /**
   * Returns the meta object for the attribute '{@link fr.pari10.miage.promo.promoDSL.Ingredient#getUnite <em>Unite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unite</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Ingredient#getUnite()
   * @see #getIngredient()
   * @generated
   */
  EAttribute getIngredient_Unite();

  /**
   * Returns the meta object for class '{@link fr.pari10.miage.promo.promoDSL.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for the attribute '{@link fr.pari10.miage.promo.promoDSL.Instruction#getNumDuInstruction <em>Num Du Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num Du Instruction</em>'.
   * @see fr.pari10.miage.promo.promoDSL.Instruction#getNumDuInstruction()
   * @see #getInstruction()
   * @generated
   */
  EAttribute getInstruction_NumDuInstruction();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PromoDSLFactory getPromoDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.pari10.miage.promo.promoDSL.impl.ModeleImpl <em>Modele</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.pari10.miage.promo.promoDSL.impl.ModeleImpl
     * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getModele()
     * @generated
     */
    EClass MODELE = eINSTANCE.getModele();

    /**
     * The meta object literal for the '<em><b>Livre</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODELE__LIVRE = eINSTANCE.getModele_Livre();

    /**
     * The meta object literal for the '{@link fr.pari10.miage.promo.promoDSL.impl.LivreImpl <em>Livre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.pari10.miage.promo.promoDSL.impl.LivreImpl
     * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getLivre()
     * @generated
     */
    EClass LIVRE = eINSTANCE.getLivre();

    /**
     * The meta object literal for the '<em><b>Nom Du Livre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIVRE__NOM_DU_LIVRE = eINSTANCE.getLivre_NomDuLivre();

    /**
     * The meta object literal for the '<em><b>Nom Du Lauteur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIVRE__NOM_DU_LAUTEUR = eINSTANCE.getLivre_NomDuLauteur();

    /**
     * The meta object literal for the '<em><b>Chapitre</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIVRE__CHAPITRE = eINSTANCE.getLivre_Chapitre();

    /**
     * The meta object literal for the '{@link fr.pari10.miage.promo.promoDSL.impl.ChapitreImpl <em>Chapitre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.pari10.miage.promo.promoDSL.impl.ChapitreImpl
     * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getChapitre()
     * @generated
     */
    EClass CHAPITRE = eINSTANCE.getChapitre();

    /**
     * The meta object literal for the '<em><b>Num Du Chapitre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAPITRE__NUM_DU_CHAPITRE = eINSTANCE.getChapitre_NumDuChapitre();

    /**
     * The meta object literal for the '<em><b>Recette</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHAPITRE__RECETTE = eINSTANCE.getChapitre_Recette();

    /**
     * The meta object literal for the '{@link fr.pari10.miage.promo.promoDSL.impl.RecetteImpl <em>Recette</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.pari10.miage.promo.promoDSL.impl.RecetteImpl
     * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getRecette()
     * @generated
     */
    EClass RECETTE = eINSTANCE.getRecette();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECETTE__NAME = eINSTANCE.getRecette_Name();

    /**
     * The meta object literal for the '<em><b>Num Photo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECETTE__NUM_PHOTO = eINSTANCE.getRecette_NumPhoto();

    /**
     * The meta object literal for the '<em><b>Ingredients</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECETTE__INGREDIENTS = eINSTANCE.getRecette_Ingredients();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECETTE__INSTRUCTIONS = eINSTANCE.getRecette_Instructions();

    /**
     * The meta object literal for the '<em><b>Alternatives</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECETTE__ALTERNATIVES = eINSTANCE.getRecette_Alternatives();

    /**
     * The meta object literal for the '{@link fr.pari10.miage.promo.promoDSL.impl.AlternativesImpl <em>Alternatives</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.pari10.miage.promo.promoDSL.impl.AlternativesImpl
     * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getAlternatives()
     * @generated
     */
    EClass ALTERNATIVES = eINSTANCE.getAlternatives();

    /**
     * The meta object literal for the '<em><b>Alt Num</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALTERNATIVES__ALT_NUM = eINSTANCE.getAlternatives_AltNum();

    /**
     * The meta object literal for the '{@link fr.pari10.miage.promo.promoDSL.impl.IngredientImpl <em>Ingredient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.pari10.miage.promo.promoDSL.impl.IngredientImpl
     * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getIngredient()
     * @generated
     */
    EClass INGREDIENT = eINSTANCE.getIngredient();

    /**
     * The meta object literal for the '<em><b>Nom Du Ing</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENT__NOM_DU_ING = eINSTANCE.getIngredient_NomDuIng();

    /**
     * The meta object literal for the '<em><b>Num</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENT__NUM = eINSTANCE.getIngredient_Num();

    /**
     * The meta object literal for the '<em><b>Unite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENT__UNITE = eINSTANCE.getIngredient_Unite();

    /**
     * The meta object literal for the '{@link fr.pari10.miage.promo.promoDSL.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.pari10.miage.promo.promoDSL.impl.InstructionImpl
     * @see fr.pari10.miage.promo.promoDSL.impl.PromoDSLPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '<em><b>Num Du Instruction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTRUCTION__NUM_DU_INSTRUCTION = eINSTANCE.getInstruction_NumDuInstruction();

  }

} //PromoDSLPackage
