/**
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.promoDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Recette</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Recette#getName <em>Name</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Recette#getNumPhoto <em>Num Photo</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Recette#getIngredients <em>Ingredients</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Recette#getInstructions <em>Instructions</em>}</li>
 *   <li>{@link fr.pari10.miage.promo.promoDSL.Recette#getAlternatives <em>Alternatives</em>}</li>
 * </ul>
 *
 * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getRecette()
 * @model
 * @generated
 */
public interface Recette extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getRecette_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.pari10.miage.promo.promoDSL.Recette#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Num Photo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num Photo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num Photo</em>' attribute.
   * @see #setNumPhoto(String)
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getRecette_NumPhoto()
   * @model
   * @generated
   */
  String getNumPhoto();

  /**
   * Sets the value of the '{@link fr.pari10.miage.promo.promoDSL.Recette#getNumPhoto <em>Num Photo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num Photo</em>' attribute.
   * @see #getNumPhoto()
   * @generated
   */
  void setNumPhoto(String value);

  /**
   * Returns the value of the '<em><b>Ingredients</b></em>' containment reference list.
   * The list contents are of type {@link fr.pari10.miage.promo.promoDSL.Ingredient}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ingredients</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ingredients</em>' containment reference list.
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getRecette_Ingredients()
   * @model containment="true"
   * @generated
   */
  EList<Ingredient> getIngredients();

  /**
   * Returns the value of the '<em><b>Instructions</b></em>' containment reference list.
   * The list contents are of type {@link fr.pari10.miage.promo.promoDSL.Instruction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Instructions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instructions</em>' containment reference list.
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getRecette_Instructions()
   * @model containment="true"
   * @generated
   */
  EList<Instruction> getInstructions();

  /**
   * Returns the value of the '<em><b>Alternatives</b></em>' containment reference list.
   * The list contents are of type {@link fr.pari10.miage.promo.promoDSL.Alternatives}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alternatives</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alternatives</em>' containment reference list.
   * @see fr.pari10.miage.promo.promoDSL.PromoDSLPackage#getRecette_Alternatives()
   * @model containment="true"
   * @generated
   */
  EList<Alternatives> getAlternatives();

} // Recette
