/*
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class PromoDSLProposalProvider extends AbstractPromoDSLProposalProvider {
}
