/*
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.ui.tests;

import com.google.inject.Injector;
import fr.pari10.miage.promo.ui.internal.PromoActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class PromoDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PromoActivator.getInstance().getInjector("fr.pari10.miage.promo.PromoDSL");
	}

}
