/*
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PromoDSLRuntimeModule extends AbstractPromoDSLRuntimeModule {
}
