/*
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.validation

import fr.pari10.miage.promo.promoDSL.Livre
import org.eclipse.xtext.validation.Check
import fr.pari10.miage.promo.promoDSL.PromoDSLPackage
import fr.pari10.miage.promo.promoDSL.Recette
import fr.pari10.miage.promo.promoDSL.Ingredient

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class PromoDSLValidator extends AbstractPromoDSLValidator {
	
  public static val Warning_auteur = "warning nom auteur"
// c''est validation
    @Check(FAST)
def verifier(Livre livre){
	if (!Character.isUpperCase(livre.nomDuLauteur.charAt(0))) {
		warning('Name should start with a capital', 
					PromoDSLPackage.Literals.LIVRE__NOM_DU_LAUTEUR,
					Warning_auteur)
	}
}

public static val Warning_Recette = "Nom du recette ne doit pas être redondant"
    @Check(NORMAL)
def verifierRectte(Livre livre){
	
	val compnots = livre.eAllContents
	.filter(typeof(Recette))
	.map[name]
	.toList
	if (compnots.stream.distinct.count!=compnots.size) {
		error("Nom du recette ne doit pas être redondant",PromoDSLPackage.Literals.LIVRE__NOM_DU_LAUTEUR,Warning_Recette)
		
	}
}

public static val Warning_Sucre = "Le Sucre doit être inferieur à 25"
    @Check(NORMAL)
def verifierSucre(Livre livre){
	
	val Recett = livre.eAllContents
	.filter(typeof(Recette))
	.toList
  for(Recette re: Recett ){
	     
	 	var nbS = 0;
	 	
       val ing = re.ingredients;
 
         for(Ingredient r:ing ){
            if (r.nomDuIng.equals("sucre")){
            	nbS = nbS+r.num;           
         }    	
         }
         if (nbS>25)
          error('Le Sucre doit être inferieur à 25', 
					PromoDSLPackage.Literals.LIVRE__NOM_DU_LAUTEUR,
					Warning_Sucre)
        }

}


}
