/*
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.tests

import com.google.inject.Inject
import fr.pari10.miage.promo.promoDSL.Promo
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(PromoDSLInjectorProvider)
class PromoDSLParsingTest{

	@Inject
	ParseHelper<Promo> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
