/*
 * generated by Xtext 2.10.0
 */
package fr.pari10.miage.promo.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PromoDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/pari10/miage/promo/parser/antlr/internal/InternalPromoDSL.tokens");
	}
}
